services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Secret5555
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data:/var/lib/mysql

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db 
    ports:
      - 8080:8080

volumes:
  mysql_db_data:
